spring:
  datasource:
    url: jdbc:mysql://13.74.242.1:23306/newyear
    username: users
    password: newyear
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

